[tool.pytest.ini_options]
pythonpath=["src"]
addopts=["--import-mode=importlib"]
asyncio_default_fixture_loop_scope="function"

[tool.ruff]
target-version = "py313"
line-length = 120

[tool.ruff.lint]
extend-select=["ALL"]
ignore=["S101","D100","D101","D102","D103","D104","D107","D203","D212","ANN201","ANN202","ANN204","ANN205","ANN401","FBT","RUF001","RUF100","PGH003","INP001","COM812","CPY001"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "single"

[tool.ruff.format]
quote-style = "single"

[tool.pyright]
typeCheckingMode = "strict"